/**
 * Generates a plain SQL seed file from the bundled curriculum.
 *
 *   npx tsx scripts/generate-seed-sql.ts
 *
 * Exists so curriculum can be loaded by pasting into the Supabase SQL Editor,
 * with no Node, no service-role key and no local checkout. The importer in
 * scripts/import-curriculum.ts remains the route for ongoing content work; this
 * is the one that gets a database populated from a browser.
 *
 * Everything is written as `liblearn` provenance with no source_id, so it
 * satisfies the provenance trigger in 0002 without claiming anything official.
 */
import {writeFileSync, mkdirSync} from 'node:fs';
import {LESSONS, TOPICS, UNITS} from '../src/data/seed/curriculum';
import {QUESTIONS, QUIZZES} from '../src/data/seed/questions';

/** Postgres string literal: double every quote. Nothing else needs escaping. */
const q = (v: string | null | undefined): string =>
  v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`;

/** jsonb literal from any value. */
const j = (v: unknown): string => `${q(JSON.stringify(v ?? []))}::jsonb`;

const out: string[] = [];
const w = (s = '') => out.push(s);

w('-- LibLearn curriculum seed — generated by scripts/generate-seed-sql.ts');
w('-- DO NOT EDIT BY HAND. Regenerate instead.');
w('--');
w('-- Run AFTER 0001_init.sql, 0002_curriculum.sql and 0003_wave2.sql.');
w('--');
w('-- Everything here is provenance \'liblearn\': academically standard teaching');
w('-- material written for LibLearn. It is NOT the Liberian national curriculum');
w('-- and must never be presented as such. Nothing carries a source_id, so the');
w('-- provenance trigger in 0002 is satisfied without any official claim.');
w('--');
w('-- Safe to run more than once: every row upserts on its primary key.');
w();
w('begin;');
w();

w('-- ---------------------------------------------------------------- units');
for (const u of UNITS) {
  w(`insert into public.units (id, subject_id, curriculum_version_id, grade, name, summary, sort_order) values
  (${q(u.id)}, ${q(u.subjectId)}, ${q(u.curriculumVersionId ?? 'liblearn-v1')}, ${u.grade}, ${q(u.name)}, ${q(u.summary)}, ${u.order})
on conflict (id) do update set name = excluded.name, summary = excluded.summary, sort_order = excluded.sort_order;`);
}
w();

w('-- --------------------------------------------------------------- topics');
for (const t of TOPICS) {
  w(`insert into public.topics (id, unit_id, subject_id, curriculum_version_id, grade, name, summary, provenance, sort_order) values
  (${q(t.id)}, ${q(t.unitId ?? null)}, ${q(t.subjectId)}, ${q(t.curriculumVersionId ?? 'liblearn-v1')}, ${t.grade}, ${q(t.name)}, ${q(t.summary)}, 'liblearn', ${t.order})
on conflict (id) do update set unit_id = excluded.unit_id, name = excluded.name, summary = excluded.summary, sort_order = excluded.sort_order;`);
}
w();

w('-- -------------------------------------------------------------- lessons');
w('-- review_status is \'published\': the repository only serves published rows.');
for (const l of LESSONS) {
  w(`insert into public.lessons (id, topic_id, subject_id, curriculum_version_id, grade, title, estimated_minutes, objectives, sections, key_terms, provenance, review_status, sort_order) values
  (${q(l.id)}, ${q(l.topicId)}, ${q(l.subjectId)}, ${q(l.curriculumVersionId ?? 'liblearn-v1')}, ${l.grade}, ${q(l.title)}, ${l.estimatedMinutes}, ${j(l.objectives)}, ${j(l.sections)}, ${j(l.keyTerms ?? [])}, 'liblearn', 'published', ${l.order})
on conflict (id) do update set title = excluded.title, objectives = excluded.objectives, sections = excluded.sections, key_terms = excluded.key_terms, review_status = excluded.review_status, sort_order = excluded.sort_order;`);
}
w();

w('-- ------------------------------------------------------------ questions');
for (const qq of QUESTIONS) {
  w(`insert into public.questions (id, topic_id, subject_id, curriculum_version_id, grade, question_type, question_text, options, correct_answer, explanation, difficulty, exam_goal, provenance, review_status) values
  (${q(qq.id)}, ${q(qq.topicId)}, ${q(qq.subjectId)}, 'liblearn-v1', ${qq.grade}, 'multiple_choice', ${q(qq.question)}, ${j(qq.options)}, ${qq.correctAnswer}, ${q(qq.explanation)}, ${q(qq.difficulty)}, ${q(qq.examGoal ?? null)}, 'liblearn', 'published')
on conflict (id) do update set question_text = excluded.question_text, options = excluded.options, correct_answer = excluded.correct_answer, explanation = excluded.explanation;`);
}
w();

w('-- -------------------------------------------------------------- quizzes');
for (const z of QUIZZES) {
  w(`insert into public.quizzes (id, lesson_id, topic_id, subject_id, grade, title) values
  (${q(z.id)}, ${q(z.lessonId ?? null)}, ${q(z.topicId)}, ${q(z.subjectId)}, ${z.grade}, ${q(z.title)})
on conflict (id) do update set title = excluded.title, lesson_id = excluded.lesson_id;`);
}
w();

w('-- ------------------------------------------------------- quiz questions');
for (const z of QUIZZES) {
  z.questionIds.forEach((qid, i) => {
    w(`insert into public.quiz_questions (quiz_id, question_id, sort_order) values (${q(z.id)}, ${q(qid)}, ${i + 1})
on conflict (quiz_id, question_id) do update set sort_order = excluded.sort_order;`);
  });
}
w();

w('commit;');
w();
w('-- Verify: expect one row per grade with non-zero counts.');
w('--   select grade, count(*) from public.topics group by grade order by grade;');
w('--   select grade, count(*) from public.lessons where review_status = \'published\' group by grade order by grade;');

mkdirSync('supabase/seed', {recursive: true});
const path = 'supabase/seed/0001_curriculum_seed.sql';
writeFileSync(path, out.join('\n') + '\n');

console.log(`Wrote ${path}`);
console.log(`  ${UNITS.length} units, ${TOPICS.length} topics, ${LESSONS.length} lessons,`);
console.log(`  ${QUESTIONS.length} questions, ${QUIZZES.length} quizzes`);
