/**
 * Builds ONE paste-able setup file: every migration in order, then the seed.
 *
 *   npx tsx scripts/generate-setup-sql.ts
 *   → supabase/liblearn-complete-setup.sql
 *
 * Why this exists. The migrations and the seed are separate files that must be
 * run in a specific order, and the seed references tables the later migrations
 * create. Run them out of order and the seed fails 500 lines in with
 * `relation "public.lesson_notes" does not exist` - a message that says what
 * broke but not what to do about it.
 *
 * Someone setting the project up through the Supabase dashboard is pasting
 * files by hand, so "remember the order" is a trap, not an instruction. One
 * file removes the ordering decision entirely.
 *
 * Every part is written to be safe to run more than once (create ... if not
 * exists, add column if not exists, guarded policy creation, and a seed that
 * upserts on primary key), so re-running the whole file is a no-op rather than
 * a duplicate-key error.
 */
import {readFileSync, writeFileSync, readdirSync} from 'node:fs';
import {join} from 'node:path';

const MIGRATIONS_DIR = 'supabase/migrations';
const SEED = 'supabase/seed/0001_curriculum_seed.sql';
const OUT = 'supabase/liblearn-complete-setup.sql';

const migrations = readdirSync(MIGRATIONS_DIR)
  .filter((f) => f.endsWith('.sql'))
  .sort(); // 0001_, 0002_, ... lexical order is the intended order

const parts: string[] = [];

parts.push(`-- ===========================================================================
-- LibLearn — COMPLETE DATABASE SETUP
--
-- Generated by scripts/generate-setup-sql.ts. DO NOT EDIT BY HAND.
--
-- Paste this whole file into the Supabase SQL Editor and run it once. It
-- contains every migration in order followed by the curriculum seed, so there
-- is no order to get wrong.
--
-- Safe to run more than once. Tables, columns and policies are created only if
-- absent, and every seeded row upserts on its primary key, so running it again
-- changes nothing and repairs anything half-applied.
--
-- Contents:
${migrations.map((m, i) => `--   ${i + 1}. ${m}`).join('\n')}
--   ${migrations.length + 1}. curriculum seed
--
-- Generated: ${new Date().toISOString().slice(0, 10)}
-- ===========================================================================
`);

for (const m of migrations) {
  const sql = readFileSync(join(MIGRATIONS_DIR, m), 'utf8').trimEnd();
  parts.push(`
-- ===========================================================================
-- MIGRATION: ${m}
-- ===========================================================================

${sql}
`);
}

// The seed carries its own begin/commit; the migrations do not. Keeping it
// intact means a failed seed rolls back without leaving the schema half-loaded.
const seed = readFileSync(SEED, 'utf8').trimEnd();
parts.push(`
-- ===========================================================================
-- SEED: curriculum content
-- ===========================================================================

${seed}
`);

// A final, readable confirmation so the person pasting this can see it worked
// without knowing which tables to go and count.
parts.push(`
-- ===========================================================================
-- VERIFY
-- ===========================================================================
select
  (select count(*) from public.lessons)       as lessons,
  (select count(*) from public.lesson_notes)  as notes,
  (select count(*) from public.questions)     as questions,
  (select count(*) from public.quizzes)       as quizzes,
  (select count(distinct grade) from public.lessons
     where review_status = 'published')       as grades_with_lessons,
  (select count(*) from public.question_note_alignment_gaps)
                                              as alignment_gaps;
-- Expect: 60 lessons, 60 notes, 164 questions, 60 quizzes, 12 grades,
--         1 alignment gap (q-alg-7, recorded as NEEDS_VERIFICATION).
`);

const out = parts.join('\n');
writeFileSync(OUT, out);

const lines = out.split('\n').length;
console.log(`Wrote ${OUT}`);
console.log(`  ${migrations.length} migration(s) + seed, ${lines} lines`);
